version: '3'
services:
  openldap:
    image: docker.io/bitnami/openldap:2.6.3
    container_name: openldap
    privileged: true
    ports:
      - 1389:1389 # LDAP  connections
      - 1636:1636 # LDAPS connections
    environment:
      LDAP_ROOT: dc=alvaro,dc=org
      LDAP_ADMIN_USERNAME: admin
      LDAP_ADMIN_PASSWORD: adminpassword
      LDAP_ALLOW_ANON_BINDING: "no"
      LDAP_CUSTOM_LDIF_DIR: /ldifs
    volumes:
      - ./ldifs:/ldifs
      # - 'openldap_data:/bitnami/openldap/'
  ldap-ui:
    image: dnknth/ldap-ui
    container_name: ldap-ui
    ports:
      - 5000:5000
    links:
      - ldap
    environment:
      LDAP_URL: "ldap://openldap:1389"
      BASE_DN: "dc=alvaro,dc=org"
      BIND_DN: "cn=admin,dc=alvaro,dc=org"
      BIND_PASSWORD: adminpassword
    restart: unless-stopped

  # phpLDAPadmin:
  #   image: osixia/phpldapadmin:0.9.0
  #   container_name: phpldapadmin
  #   # privileged: true
  #   ports:
  #     - 8080:80
  #   environment:
  #     # PHPLDAPADMIN_LDAP_HOSTS_FRIENDLY: "#PYTHON2BASH:[{'openldap': [{'server': [{'tls': False}, {'host': 'localhost'}, {'port': 1389}]}, {'login': [{'bind_id': 'cn=admin,dc=alvaro,dc=org'}, {'bind_pass': 'adminpassword'}]}]}]"
  #     PHPLDAPADMIN_LDAP_HOSTS: openldap
  #     # PHPLDAPADMIN_LDAP_HOSTS: "#PYTHON2BASH:[{'openldap': [{'server': [{'tls': False}, {'port': 1389}]}]}]"
  #     PHPLDAPADMIN_HTTPS: "false"
# volumes:
#   openldap_data:
#     driver: local
