version: '3'
services:
  openldap:
    image: docker.io/bitnami/openldap:2.6.3
    container_name: openldap
    privileged: true
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      LDAP_ROOT: 'dc=alvaro,dc=org'
      LDAP_ADMIN_USERNAME: "admin"
      LDAP_ADMIN_PASSWORD: "adminpassword"
      # LDAP_USERS: "user01,user02"
      # LDAP_PASSWORDS: "password1,password2"
      LDAP_ALLOW_ANON_BINDING: "no"
      LDAP_CUSTOM_LDIF_DIR: /ldifs
    volumes:
      - ./init/users.ldif:/ldifs/users.ldif
      # - 'openldap_persist:/bitnami/openldap/'
  # myapp:
  #   image: registry.redhat.io/datagrid/datagrid-8-rhel8:1.3
  #   ports:
  #     - '11222:11222'
# volumes:
#   openldap_data:
#     driver: local
