version: '3'
services:
  openldap:
    image: docker.io/bitnami/openldap:2.6.3
    container_name: openldap
    privileged: true
    ports:
      - 1389:1389 # LDAP  connections
      - 1636:1636 # LDAPS connections
    environment:
      LDAP_ROOT: dc=acme,dc=org
      LDAP_ADMIN_USERNAME: admin
      LDAP_ADMIN_PASSWORD: adminpassword
      LDAP_ALLOW_ANON_BINDING: "no"
      LDAP_CUSTOM_LDIF_DIR: /ldifs
      # BITNAMI_DEBUG: true
    volumes:
      - ./ldifs:/ldifs
      # - 'openldap_data:/bitnami/openldap/'
  ldap-ui:
    image: dnknth/ldap-ui
    container_name: ldap-ui
    ports:
      - 5000:5000
    links:
      - openldap
    environment:
      LDAP_URL: "ldap://openldap:1389"
      BASE_DN: "dc=acme,dc=org"
      BIND_DN: "cn=admin,dc=acme,dc=org"
      BIND_PASSWORD: adminpassword
    depends_on:
      - openldap
    restart: unless-stopped

  rhdg:
    # image: registry.redhat.io/datagrid/datagrid-8-rhel8:1.3
    image: registry.redhat.io/datagrid/datagrid-8-rhel8:1.4-8.4.1.GA.1
    container_name: rhdg
    hostname: rhdg
    privileged: true
    ports:
      - 11222:11222
    volumes:
      - ./rhdg:/opt/infinispan/server/conf/user
    command:
      - '-Dinfinispan.zero-capacity-node=false'
      - '-l'
      - /opt/infinispan/server/conf/user/log4j.xml
      # - '-c'
      # - user/infinispan-base.xml
      # - '-c'
      # - user/infinispan-config.yaml
      # - '-c'
      # - user/infinispan-admin.xml
      # - '-c'
      # - user/infinispan-custom.xml
      - '-c'
      - user/infinispan-custom.yml
    depends_on:
      - openldap
    restart: unless-stopped
