= OpenLDAP Playground
Álvaro López Medina <alopezme@redhat.com>
v1.0, 2022-10
// Metadata
:description: This document shows how to deploy a basic openldap container and a UI and initialize it with some users and groups.
:keywords: openldap, ldap, playground, red hat
// Create TOC wherever needed
:toc: macro
:sectanchors:
:sectnumlevels: 2
:sectnums: 
:source-highlighter: pygments
:imagesdir: images
// Start: Enable admonition icons
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
ifndef::env-github[]
:icons: font
endif::[]
// End: Enable admonition icons
// Create the Table of contents here
toc::[]

== Introduction

https://openldap.org/[OpenLDAP] is a free, open-source implementation of the Lightweight Directory Access Protocol (LDAP) developed by the OpenLDAP Project.

https://www.rfc-editor.org/rfc/rfc4511[LDAP] stands for Lightweight Directory Access Protocol. As the name suggests, it is a lightweight protocol for accessing directory services, specifically X.500-based directory services. LDAP runs over TCP/IP or other connection oriented transfer services. 

=== Server

In order to simplify installation and usage, we are going to use a public https://hub.docker.com/r/bitnami/openldap/[OpenLDAP container image] published by Bitnami.

To deploy OpenLDAP in a simple manner, we are going to use the command `podman-compose`. https://docs.docker.com/compose/[Compose] is a tool for defining and running multi-container applications. With Compose, you use a YAML file to configure your application's services. Then, with a single command, you create and start all the services from your configuration. 

NOTE: Podman compose is included in your default podman installation.


=== Client utilities

It is strongly recommended to install https://docs.fedoraproject.org/en-US/fedora/latest/system-administrators-guide/servers/Directory_Servers/#s2-ldap-installation[`openldap-clients`], which is a package containing the command line utilities for viewing and modifying directories on an LDAP server. Amongst others, you will have `ldapsearch` to search LDAP directory entries.


=== Web Interface

One of the downsides of OpenLDAP for beginners, compared with other LDAP solutions such as FreeIPA or MS Active Directory, is that it does not come with a default web console to configure and check users, groups, etc. For that purpose, there are many open source projects that can help us to solve that issue:

* https://phpldapadmin.sourceforge.net/wiki/index.php/Main_Page[*phpLDAPadmin*]: It provides easy, anywhere-accessible, multi-language administration for your LDAP server. The problem is that its development seems stale on GitHub and might not provide the latest features or bug solutions.
* https://github.com/dnknth/ldap-ui[*ldap-ui*]: This is a minimal interface, but it is under constant development.

Therefore, we are going to try *ldap-ui*, which might be simpler and fancier.



== Basic podman compose commands

=== Run the server

Run the server in detach mode, which is running the container in the background, printing the new container name.

[source, bash]
----
podman-compose up --detach
----

=== Obtain the LDAP logs
[source, bash]
----
podman logs --follow openldap
----

=== Shutdown and remove the container
[source, bash]
----
podman-compose down
----


== Using ldapsearch to check users list

.Using LDAP
[source, bash]
----
# List all
ldapsearch -H ldap://localhost:1389 -x -b "dc=acme,dc=org" -D "cn=admin,dc=acme,dc=org" -w adminpassword

# List all users
ldapsearch -H ldap://localhost:1389 -x -b "dc=acme,dc=org" -D "cn=admin,dc=acme,dc=org" -w adminpassword "objectclass=person" 

# List all groups
ldapsearch -H ldap://localhost:1389 -x -b "dc=acme,dc=org" -D "cn=admin,dc=acme,dc=org" -w adminpassword "objectclass=groupOfNames"

# List all users of the Admins group
ldapsearch -H ldap://localhost:1389 -x -b "cn=admins,ou=groups,dc=acme,dc=org" -D "cn=admin,dc=acme,dc=org" -w adminpassword member
----
////

.Using LDAPS
[source, bash]
----
# List all Users
ldapsearch -H ldaps://localhost:1636 -x -b "dc=acme,dc=org" -D "cn=admin,dc=acme,dc=org" -w adminpassword


ldapsearch -x -D "ldap_user" -w "user_passwd" -b "cn=jdoe,dc=example,dc=local" -h ldap_host **memberof**

# Request StartTLS
ldapsearch -H ldap://localhost:10389 -Z -x -b "ou=people,dc=planetexpress,dc=com" -D "cn=admin,dc=planetexpress,dc=com" -w GoodNewsEveryone "(objectClass=inetOrgPerson)"

# Enforce StartTLS
ldapsearch -H ldap://localhost:10389 -ZZ -x -b "ou=people,dc=planetexpress,dc=com" -D "cn=admin,dc=planetexpress,dc=com" -w GoodNewsEveryone "(objectClass=inetOrgPerson)"

# Enforce StartTLS with self-signed cert
LDAPTLS_REQCERT=never ldapsearch -H ldap://localhost:10389 -ZZ -x -b "ou=people,dc=planetexpress,dc=com" -D "cn=admin,dc=planetexpress,dc=com" -w GoodNewsEveryone "(objectClass=inetOrgPerson)"
----
////



== Known issues

The OpenLDAP container still requires privileged permissions to execute. If not, the `ldif` file is not mounted with the correct permissions and you obtain an error like this:

[source, console]
----
podman logs openldap
 15:44:02.04 INFO  ==> ** Starting LDAP setup **
 15:44:02.06 INFO  ==> Validating settings in LDAP_* env vars
 15:44:02.06 INFO  ==> Initializing OpenLDAP...
 15:44:02.08 INFO  ==> Creating LDAP online configuration
 15:44:02.09 INFO  ==> Starting OpenLDAP server in background
 15:44:03.11 INFO  ==> Configure LDAP credentials for admin user
 15:44:03.14 INFO  ==> Adding LDAP extra schemas
ls: cannot open directory '/ldifs': Permission denied
 15:44:03.17 INFO  ==> Creating LDAP default tree
 15:44:04.24 INFO  ==> ** LDAP setup finished! **
----



== References


* https://devconnected.com/how-to-search-ldap-using-ldapsearch-examples/[How To Search LDAP using ldapsearch].
* https://github.com/wfink/infinispan.playground.security[Wolf's LDAP Playground].
* https://github.com/bitnami/containers/blob/main/bitnami/openldap/README.md[OpenLDAP container Readme file].


* Red Hat Data Grid documentation: 
** https://access.redhat.com/documentation/en-us/red_hat_data_grid/8.3/html/data_grid_security_guide/security-realms#ldap-security-realms_security-realms[LDAP Server Security Realm].
** https://access.redhat.com/documentation/en-us/red_hat_data_grid/8.3/html-single/configuring_data_grid_caches/index#configuring-cache-authorization_security-authorization[Securing caches].
** https://access.redhat.com/webassets/avalon/d/red-hat-data-grid/8.3/configdocs/infinispan-config-13.0.html#[Cache Security Schema].


== How to deploy on OCP

* https://docs.bitnami.com/tutorials/create-openldap-server-kubernetes/[Create An OpenLDAP server with Bitnami Containers on Kubernetes].
* https://www.talkingquickly.co.uk/installing-openldap-kubernetes-helm[Installing OpenLDAP on Kubernetes with Helm].
