infinispan:
  server:
    interfaces:
      interface:
         name: public
         inet-address:
            value: "${infinispan.bind.address:127.0.0.1}"
    socket-bindings:
      default-interface: public
      port-offset: "${infinispan.socket.binding.port-offset:0}"
      socket-binding:
         name: default
         port: "${infinispan.bind.port:11222}"

    security:
      security-realms:
        security-realm:
          name: ldap-realm
          ldap-realm:
            url: ldap://openldap:1389
            # url: ldap://openldap-service.openldap.svc:1389
            principal: "cn=admin,dc=acme,dc=org"
            credential: adminpassword
            direct-verification: true
            identity-mapping:
              rdnIdentifier: uid
              searchDn: "ou=clients,dc=acme,dc=org"
              userPasswordMapper:
                from: userPassword
                verifiable: false
              attributeMapping:
                - from: cn
                  to: Roles
                  filter: "(&(objectClass=groupOfNames)(member={1}))"
                  filterDn: "ou=roles,dc=acme,dc=org"
    endpoints:
      endpoint:
        socket-binding: default
        security-realm: ldap-realm
        hotrod-connector:
          authentication:
            sasl:
              qop: auth
              server-name: infinispan
              mechanisms: BASIC DIGEST PLAIN DIGEST-MD5
        rest-connector:
          authentication:
            mechanisms: DIGEST BASIC
